#!/usr/bin/env python3
"""Export data/cases.py to: src/cases/<slug>.json (video data), voiceover/<slug>.txt (text to record),
and DESCRIPTIONS.md (TikTok captions)."""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "data"))
from cases import CASES  # noqa: E402

(ROOT / "src" / "cases").mkdir(parents=True, exist_ok=True)
(ROOT / "voiceover").mkdir(exist_ok=True)
index, desc, vo = [], ["# TikTok captions\n"], ["# Voice-over scripts\n\nOne recording per video. Read the lines in order with a pause of about one second between them.\n"]
for n, c in enumerate(CASES, 1):
    lines = [{"id": f"s{i:02d}", "text": l["text"], "v": l["v"]} for i, l in enumerate(c["lines"], 1)]
    (ROOT / "src" / "cases" / f"{c['slug']}.json").write_text(
        json.dumps({"slug": c["slug"], "title": c["title"], "place": c["place"], "year": c["year"], "lines": lines}, ensure_ascii=False, indent=1),
        encoding="utf-8")
    (ROOT / "voiceover" / f"{n:02d}-{c['slug']}.txt").write_text(
        f"{c['title']} ({c['year']}, {c['place']})\n"
        "Read in order, with a pause of about one second between lines. Tone: calm, serious true-crime narrator.\n\n"
        + "\n\n".join(l["text"] for l in c["lines"]) + "\n", encoding="utf-8")
    vo.append(f"## {n:02d}. {c['title'].title()} ({c['year']}, {c['place'].title()})\n\n" + "\n\n".join(l["text"] for l in c["lines"]) + "\n")
    d = c["description"]
    desc.append(f"## {n:02d}. {c['title'].title()} ({c['year']})\n\n**Title:** {d['title']}\n\n{d['body']}\n\n"
                f"Follow for more unsolved mysteries.\n\n{' '.join(d['tags'])}\n")
    index.append(c["slug"])
(ROOT / "DESCRIPTIONS.md").write_text("\n".join(desc), encoding="utf-8")
(ROOT / "VOICEOVERS.md").write_text("\n".join(vo), encoding="utf-8")
# Registry imported by the Remotion compositions (one per case).
reg = ["// Generated by scripts/export-cases.py — do not edit by hand.", "import type {CaseData, Timings} from './CaseVideo';"]
for i, slug in enumerate(index):
    reg.append(f"import c{i} from './cases/{slug}.json';")
    reg.append(f"import t{i} from './timings/{slug}.json';")
reg.append("export const CASES: {data: CaseData; timings: Timings}[] = [")
reg += [f"  {{data: c{i} as CaseData, timings: t{i} as Timings}}," for i in range(len(index))]
reg.append("];")
(ROOT / "src" / "registry.ts").write_text("\n".join(reg) + "\n", encoding="utf-8")
print(f"{len(index)} cases exported")
