// Generated by scripts/export-cases.py — do not edit by hand.
import type {CaseData, Timings} from './CaseVideo';
import c0 from './cases/jack-the-ripper.json';
import t0 from './timings/jack-the-ripper.json';
import c1 from './cases/villisca-axe-murders.json';
import t1 from './timings/villisca-axe-murders.json';
import c2 from './cases/hinterkaifeck.json';
import t2 from './timings/hinterkaifeck.json';
import c3 from './cases/cleveland-torso-murders.json';
import t3 from './timings/cleveland-torso-murders.json';
import c4 from './cases/black-dahlia.json';
import t4 from './timings/black-dahlia.json';
import c5 from './cases/taman-shud.json';
import t5 from './timings/taman-shud.json';
import c6 from './cases/dyatlov-pass.json';
import t6 from './timings/dyatlov-pass.json';
import c7 from './cases/beaumont-children.json';
import t7 from './timings/beaumont-children.json';
import c8 from './cases/zodiac-killer.json';
import t8 from './timings/zodiac-killer.json';
import c9 from './cases/monster-of-florence.json';
import t9 from './timings/monster-of-florence.json';
import c10 from './cases/isdal-woman.json';
import t10 from './timings/isdal-woman.json';
import c11 from './cases/db-cooper.json';
import t11 from './timings/db-cooper.json';
import c12 from './cases/alphabet-murders.json';
import t12 from './timings/alphabet-murders.json';
import c13 from './cases/oakland-county-child-killer.json';
import t13 from './timings/oakland-county-child-killer.json';
import c14 from './cases/burger-chef-murders.json';
import t14 from './timings/burger-chef-murders.json';
import c15 from './cases/chicago-tylenol-murders.json';
import t15 from './timings/chicago-tylenol-murders.json';
import c16 from './cases/jonbenet-ramsey.json';
import t16 from './timings/jonbenet-ramsey.json';
import c17 from './cases/notorious-big.json';
import t17 from './timings/notorious-big.json';
import c18 from './cases/setagaya-family-murder.json';
import t18 from './timings/setagaya-family-murder.json';
import c19 from './cases/madeleine-mccann.json';
import t19 from './timings/madeleine-mccann.json';
export const CASES: {data: CaseData; timings: Timings}[] = [
  {data: c0 as CaseData, timings: t0 as Timings},
  {data: c1 as CaseData, timings: t1 as Timings},
  {data: c2 as CaseData, timings: t2 as Timings},
  {data: c3 as CaseData, timings: t3 as Timings},
  {data: c4 as CaseData, timings: t4 as Timings},
  {data: c5 as CaseData, timings: t5 as Timings},
  {data: c6 as CaseData, timings: t6 as Timings},
  {data: c7 as CaseData, timings: t7 as Timings},
  {data: c8 as CaseData, timings: t8 as Timings},
  {data: c9 as CaseData, timings: t9 as Timings},
  {data: c10 as CaseData, timings: t10 as Timings},
  {data: c11 as CaseData, timings: t11 as Timings},
  {data: c12 as CaseData, timings: t12 as Timings},
  {data: c13 as CaseData, timings: t13 as Timings},
  {data: c14 as CaseData, timings: t14 as Timings},
  {data: c15 as CaseData, timings: t15 as Timings},
  {data: c16 as CaseData, timings: t16 as Timings},
  {data: c17 as CaseData, timings: t17 as Timings},
  {data: c18 as CaseData, timings: t18 as Timings},
  {data: c19 as CaseData, timings: t19 as Timings},
];
